name: Basic Build & Test

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore

      - name: Format
        run: dotnet format --no-restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Install SQL Server
        uses: Particular/install-sql-server-action@v1.2.0
        with:
          connection-string-env-var: TEST_CONNECTION_STRING
          catalog: mono-sql-dev
          extra-params: "TrustServerCertificate=true;"

      - name: Test
        run: dotnet test --no-build --verbosity normal -c Release /p:CollectCoverage=true /p:Threshold=100 /p:ThresholdType=branch