name: Deploy Master to Development

on:
  push:
    branches: [master]

env:
  PACKAGE_PATH: './app-package'
  APP_NAME: app-mono-dev
  PUBLISH_PROFILE: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore

      - name: Format
        run: dotnet format --no-restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Test
        run: dotnet test --no-build --verbosity normal -c Release /p:CollectCoverage=true /p:Threshold=100 /p:ThresholdType=branch

      - name: Publish
        run: dotnet publish -c Release -o ${{ env.PACKAGE_PATH }}

      - name: Deploy
        uses: azure/webapps-deploy@v2
        env:
          development: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        with:
          app-name: ${{ env.APP_NAME }}
          publish-profile: ${{ env.PUBLISH_PROFILE }}
          package: ${{ env.PACKAGE_PATH }}